[package]
name = "fls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.18"
crossterm = { version = "0.23.2", features = ["event-stream"]}

tokio = { version = "1", features = ["full"] }
futures = "0.3.21"

fuzzy-matcher = "0.3.7"
open = "2.1.3"
jwalk = "0.6.0"
